FROM python:3.7-alpine

WORKDIR /projet

COPY requirements.txt /
ADD download.py /
RUN apk update && apk add python3-dev \ 
                               gcc \
                               libc-dev
RUN pip install --upgrade pip \
    pip install -r requirements.txt

CMD [ "python", "./download.py" ]

