version: '3.7'
services:

  download:
    container_name: tdm_download
    build: Dockerfile_donwload
    restart: unless-stopped
    network_mode: host
    volumes:
      - images-data:/home/images

  acquisition:
    container_name: tdm_acquisition
    build: Dockerfile_acquisition
    restart: unless-stopped
    working_dir: /project
    network_mode: host
    volumes:
      - images-data:/home/images
    depends_on:
      - download
      
  analysis:
    container_name: tdm_analysis
    build: Dockerfile_analysis
    restart: unless-stopped
    working_dir: /project
    network_mode: host
    volumes:
        - images-data:/home/images
    depends_on:
      - acquisition

  recommendation:
    container_name: tdm_recommandation
    build: Dockerfile_recommendation
    restart: unless-stopped
    working_dir: /project
    network_mode: host
    volumes:
      - images-data:/home/images
    depends_on:
      - analysis
   
volumes:
  images-data:
  requirement-data: