FROM python:3.7-alpine

WORKDIR /projet

COPY requirements.txt /
ADD recommendation.py /
RUN apk update && apk add python3-dev \ 
                               gcc \
                               libc-dev
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

CMD [ "python", "./recommendation.py" ]

